dist: xenial
language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
go_import_path: github.com/bitly/oauth2_proxy
install:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
script:
  - ./test.sh
branches:
  only:
  - master
notifications:
  email: false
