dist: xenial
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
go_import_path: github.com/ploxiln/oauth2_proxy
install:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure -v
  - go build
script:
  - ./test.sh
branches:
  only:
  - master
notifications:
  email: false
